version: '3'

services:
  app:
    image: app:1.0
    expose:
      - "80"
    environment:
      - HOST_NAME=gp1f4act14

  lb:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    ports:
      - "80:80"  
    links:
      - app
